media:
  - { name: media-portfolio, label: "Media (Portfolio)", input: files/media/media-portfolio, output: /media }
  - { name: media-blog, label: "Media (Blog)", input: files/media/media-blog, output: /media }
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/blog
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: author, label: Author, type: string }
      - { name: pubDatetime, label: Date, type: date }
      - { name: modDatetime, label: Date, type: date }
      - { name: title, label: Title, type: string, required: true }
      - { name: ogImage, label: Title, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: draft, label: Draft, type: boolean }
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }
  - name: about
    label: About page
    type: file
    path: src/pages/about.md
    fields:
      - { name: tags, label: Tags, type: string, list: true }
      - { name: title, label: Title, type: string, required: true }
      - { name: layout, type: string, hidden: true, default: "../layouts/AboutLayout.astro" }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }
